services:

  postgres:
    container_name: postgres-pregnancytracker
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

#  pgadmin:
#    container_name: pgadmin-spring-data
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    restart: unless-stopped


volumes:
  postgres:
  pgadmin:


#
#    version: '3.8'
#    services:
#      application:
#        build: .             # `docker-compose up --build` will read the Dockerfile
#        ports: [ '8080:8080' ] # host:container port
#        environment:
#          - SPRING_DATASOURCE_URL=jdbc:postgresql://db/product_db
#          - SPRING_DATASOURCE_USERNAME=postgres
#          - SPRING_DATASOURCE_PASSWORD=********
#      db:
#        image: postgres:14   # from Docker Hub, not built locally
#        ports: [ '5432:5432' ] # optional
#        volumes: # persist database data across restarts
#          - dbdata:/var/lib/postgresql/data
#        environment:
#          - POSTGRES_DB=product_db
#          - POSTGRES_USER=postgres
#          - POSTGRES_PASSWORD=********
#    volumes:
#      dbdata:                # no particular settings for this volume